name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g. 1.0.7)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and Upload
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
        with:
          args: -r ${{ github.event.inputs.version }}
